name: Deploy
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build -t tanpisitpt/s10-client -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true tanpisitpt/s10-client npm test

      - name: build client image
        run: docker build -t tanpisitpt/s10-client ./client
      - name: build nginx image
        run: docker build -t tanpisitpt/s10-nginx ./nginx
      - name: build server image
        run: docker build -t tanpisitpt/s10-server ./server
      - name: build worker image
        run: docker build -t tanpisitpt/s10-worker ./worker

      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push tanpisitpt/s10-client
      - run: docker push tanpisitpt/s10-nginx
      - run: docker push tanpisitpt/s10-server
      - run: docker push tanpisitpt/s10-worker

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multi-docker
          environment_name: Multidocker-env
          existing_bucket_name: elasticbeanstalk-ap-southeast-1-532792856393
          region: ap-southeast-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
